name: Sync to GitLab

on:
  push:
    branches:
      - main  # Trigger on push to the main branch

jobs:
  sync:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout GitHub repository
        uses: actions/checkout@v2

      - name: Set up Git
        run: |
          git config --global user.name "GitHub Actions"
          git config --global user.email "actions@github.com"

      - name: Add GitLab remote
        run: |
          git remote add gitlab https://oauth2:${{ secrets.GITLAB_TOKEN }}@${{ secrets.GITLAB_REPO_URL }}
        
      - name: Push to GitLab
        run: |
          git push gitlab main  # You can change "main" to any branch you want to sync
